### ISSUE TITLE
Compatibility with DJlint

### ISSUE THREAD

**Issue by rphlo** [adamchainz/djade#101]
## Feature Request
Hi, First thanks for this project,
Here is my request.

Before using this I was already using https://github.com/djlint/djLint and it has conflicting formatting rules regarding django jinja templates.
Biggest conflict is regarding white lines around `{% block %}`, smaller conflict is about naming inlines `{% endblock %}`

Would be nice to see a common approach regarding those.

I posted a feature request as well in djLint repo.

https://github.com/djlint/djLint/issues/1021

**Comment by adamchainz** [comment]
I'm not planning on adding compatibility with djlint. Its approach is also not 100% semantically safe - adjusting whitespace can break HTML, as noted in the [formatting guide](https://github.com/adamchainz/djade?tab=readme-ov-file#formatting).

I advise that you use only one formatter for your templates.
