### ISSUE TITLE
Documented recursive command not working when no html file is found

### ISSUE THREAD

**Issue by niccolomineo** [adamchainz/djade#105]
### Package Version

1.3.2

### Description

On a fresh Django install, I am getting the following:

```shell
$ git ls-files -z -- '*.html' | xargs -0 djade
error: the following required arguments were not provided:
  <FILENAMES>...

Usage: djade --target-version <TARGET_VERSION> <FILENAMES>...
```

If I add an empty `.html` file to the project, it works again.

**Comment by niccolomineo** [comment]
I silenced the error this way:

```shell
find . -name '*.html' -exec djade --target-version 5.1 {} \;
```

**Comment by adamchainz** [comment]
The `-r` option for `xargs` can also avoid this issue. I have added that to the example in the README, and in django-upgrade, and to my [related blog post](https://adamj.eu/tech/2022/03/09/how-to-run-a-command-on-many-files-in-your-git-repository/).
