### ISSUE TITLE
Universal newlines

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/djade#71]
### Description

Detect which comes first in a file: `\n` or `\r\n`. Use the result for wherever Djade adds newlines, such as in `update_leading_trailing_whitespace()` and `update_top_level_block_spacing()`.

Check `LEADING_BLANK_LINES` matches `\r`.

**Comment by georgeyk** [comment]
hi @adamchainz - I'm learning rust atm (~75% on  "the book"), do you mind if I take a stab at it?

**Comment by adamchainz** [comment]
Sure, remember to add tests. The detection should be called in format(), before lex().

**Comment by georgeyk** [comment]
I need to run a few more tests, but ready for early feedback. ^
