### ISSUE TITLE
Detect (and remove) unused loaded template tags

### ISSUE THREAD

**Issue by GitRon** [adamchainz/djade#75]
### Description

Hi @adamchainz!

After running your linter and effectiveley changing every single template file in my project, I detected a bunch of them loading template tags which weren't used. 

Since the loading doesn't inherit (AFAIK) to includes, do you think it would be possible to detect and remove unused "imports"?

Best from Cologne  
Ronny

**Comment by adamchainz** [comment]
It’s not possible in general because Djade doesn't run Python code, so it can't discover which tags and filters come from which libraries.

The `--builtin` option suggested in #43 will allow removal of some libraries though.

**Comment by GitRon** [comment]
Ah, I understand! Thx for the heads up. 👍
