### ISSUE TITLE
Avoid dedenting top-level blocks under `{% if %}` tags in `{% extends %}` templates

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/djade#76]
### Package Version

1.1.1

### Description

Currently, Djade does this:

```diff
 {% extends 'engine.html' %}

 {% if red %}
-  {% block boiler %}
+{% block boiler %}
     ...
-  {% endblock boiler %}
+{% endblock boiler %}
 {% endif %}
```

Which fights with DjHTML, which will reindent it.

The `{% block %}` here isn't actually top-level, so should be left alone.

We can't really handle *all* wrapping tags, since we can't know about custom tags, but we can handle `{% if %}` and other built-ins.

**Comment by knyghty** [comment]
I know you'd like to have as little configuration as possible, and I agree with that, but maybe here it's worth it. At the moment I'm using djLint's formatter, which allows you to specify any custom wrapping tags, e.g:

```toml
[tool.djlint]
custom_blocks = "partialdef,flag"
```

This works fairly well.

**Comment by adamchainz** [comment]
Yes, fair. Do you use those tags around top-level blocks?

**Comment by knyghty** [comment]
Not currently but I can imagine a scenario where I'd only want to override a block if a flag is on.
