### ISSUE TITLE
Error reading templates/**/*.html

### ISSUE THREAD

**Issue by Macktireh** [adamchainz/djade#83]
### Package Version

1.2.0

### OS

Windows 11

### Description

Hi Adam,

I don’t understand why `templates/**/*.html` isn’t working.

![image](https://github.com/user-attachments/assets/cc9016d6-b584-4738-ab57-d97d4287cff9)

Thank you

**Comment by adamchainz** [comment]
That is shell-specific syntax, it seems it does not work on your shell, which is PowerShell I think. You need to find the specific syntax for your shell.

**Comment by Macktireh** [comment]
Yes, I found

```ps1
pdm run djade.exe --target-version 5.1 (Get-ChildItem templates -Recurse -Filter *.html).FullName
```

**Comment by Macktireh** [comment]
Maybe it would be helpful to specify that in the README.

**Comment by adamchainz** [comment]
I went the other way and dropped the globbing from the examples in 1a9a8ee2e55216f9dba995cb027cc6d7515bad9b
