### ISSUE TITLE
Unexpected whitespace changes inside block

### ISSUE THREAD

**Issue by gav-fyi** [adamchainz/djade#88]
### Package Version

1.2.0

### Description

First, I'd like to say great effort in creating this package. Template handling was always on my `django-upgrade` wish list so seeing a package to tackle these is great. 

I've ran it against a few projects (some with 100s of templates) and it mostly works great. I've only actually spotted one potential issue. It didn't _actually_ affect us as our base template also adds extra spaces, but I could see how it could have caused issues.

-----

Djade seems to be stripping some intentional whitespace from within a one-line block which could cause issues with class names. 

Within our "class" blocks, we always add spaces before and after a class name to avoid clashes with the base template.. 

```html
{% extends 'base.html' %}                                                                                                                                                                

{% block body-class %}{{ block.super }} my-class {% endblock %}
```

Djade reformatted this file to strip any trailing spaces. 

```html
{% extends 'base.html' %}                                                                                                                                                                

{% block body-class %}{{ block.super }} my-class{% endblock %}
```

I wouldn't have expected Djade to reformat the block's contents.

**Comment by adamchainz** [comment]
Thank you for the clear bug report. I have a fix in #90, releasing shortly.
