### ISSUE TITLE
Formatting issue with custom filter

### ISSUE THREAD

**Issue by roxanebellot** [adamchainz/djade#92]
### Package Version

1.2.0

### Description

Hi, encountered a case. i have a QuerySet of _tips_, that have an attribute _excerpt_, and a custom filter to limit display at 240 chars

`{{ tips[0].excerpt|customLimitFilter: 240 }}`

is formatted in 

`{{ tips }}`

Causing a little change in display. :sweat_smile: 

For reference, we use djade with 

``
find . -name "*.html" | xargs djade --target-version `python -m django --version  | grep -oP "\d.\d+"  
``
    

Thank you

**Comment by gav-fyi** [comment]
Does `{{ tips[0] }}` actually work? I thought that was invalid syntax and indexes in Django templates had to be `{{ tips.0 }}`.

**Comment by adamchainz** [comment]
Djade aims not to break syntactically incorrect templates. In this case, the branch to preserve unparsed variables was broken. Thanks for the report @roxanebellot , fixed in #93 and released in 1.3.1.
